### ISSUE TITLE
Internal Server Error on Reddit login

### ISSUE THREAD

**Issue by chiefnoah** [dxprog/anime-bracket#14]
Getting a 500 error when I try to log in with my reddit account. Spamming reload a few times occasionally gets it to work.

**Comment by dxprog** [comment]
Thanks for the heads up. Apparently, reddit is now rate limiting the Guzzle user agent (which is used by my OAuth dependency). I've hard coded something else in and it seems to be fine now. Re-open this ticket if you continue to see issues.
