### ISSUE TITLE
[Enhancement] Add the ability to click on source URLs

### ISSUE THREAD

**Issue by ifonefox** [dxprog/anime-bracket#27]
Right now, [/r/visualnovels is running a "most desired VN English Translation" bracket](https://animebracket.com/vote/r-visualnovels-most-desired-vn-english-translation/). In it, the "source" for each entry is a link to it's VNDB page. Since the source is just text, clicking on it makes you vote for the entry, instead of opening a link. It would be great if there were a way to add hyperlinks to the source of an entry.

**Comment by dxprog** [comment]
In similar vein, there's a desire for embeddables that I quite like and has been implemented as a UserScript by /u/starg09 found [here](https://gist.github.com/starg09/737860a2ec85c5962eeff248f068fc56). I think I'll roll both of these ideas together.

**Comment by dxprog** [comment]
A URL can now be added when creating entrants in the process nominees form. This will be displayed on voting/character pages.
