### ISSUE TITLE
Votes not consistent after refreshing page

### ISSUE THREAD

**Issue by Ghostkeeper** [dxprog/anime-bracket#32]
I'm currently voting here: https://animebracket.com/vote/best-girl-6-starting-salt-in-another-contest/
After I submitted my votes, I got a message that the Captcha failed, which is correct because I block scripts from Google by default and so it didn't display that Captcha for me. I temporarily allowed Google in my NoScript which refreshed the page. After the refresh though, the votes that were cast on the candidates were in some cases switched because the candidates are switched from left to right randomly.

**Steps to reproduce:**
1. Cast a few votes in a voting page.
2. Before submitting the votes, refresh the page.

**Expected results:**
* Some candidates may have swapped positions randomly. I understand that this is good for the neutrality of left-right bias in the votes.
* Votes that were cast prior to refreshing must also swap if the candidates swapped.

**Actual results:**
* Some candidates were indeed swapped, however...
* The check marks on the candidates did not swap, causing different characters to be selected if you were to immediately submit the votes.

**Comment by dxprog** [comment]
Thanks for the detailed write up! I can't repro this to save my life, though:

- Logged in
- Went to Best Girl 6 bracket
- Selected some entrants
- Attempted to submit votes without captcha
- Got "captcha failed" error
- Checked selected entrants, no change. No sides swapped (makes sense since this is not a full page refresh)
- Did a full page refresh
- No entrants are checked

Did a few variations of the above, no dice. This is what I'd expect since selections are not saved between page loads _unless_ those votes have been submitted. What's your browser?

**Comment by Ghostkeeper** [comment]
Ah, so maybe the bug is then that the selections are not erased when refreshing. If they would be erased, it'll at least be more clear that the votes are not correct any more.

My browser is Firefox 67.0.2, 64-bit on Windows (currently up to date).

**Comment by dxprog** [comment]
> If they would be erased, it'll at least be more clear that the votes are not correct any more.

That's exactly what it _does_ do. As I mentioned in my comment above, only submitted votes are saved between page loads. Nothing else is. I'll give a look in firefox and see if it's trying to be smart but really being dumb.

**Comment by Ghostkeeper** [comment]
According to [this](https://stackoverflow.com/questions/7377301/firefox-keeps-form-data-on-reload), the form `<input>` entries get autocompleted when refreshing the page, with what the user previously filled in before refreshing. The [specification](https://www.w3.org/TR/html52/sec-forms.html#enabling-clientside-automatic-filling-of-form-controls) says that the behaviour here is up to the browser.

**Comment by dxprog** [comment]
Nice catch, man. PR's been merged and pushed to production. Thanks again!

**Comment by Ghostkeeper** [comment]
It works in production too! Thanks for handling it so quickly.
