### ISSUE TITLE
"Lost To" column in Entrant Statistics does not appear for ties

### ISSUE THREAD

**Issue by magic-shortcake** [dxprog/anime-bracket#65]
If a match results in a tie, the winner is determined by seed. However, the losing entrant with the lower seed does not get their "Lost To" column filled in the Entrant Statistics. It stays blank, as if they were not yet eliminated.

**Comment by dxprog** [comment]
@magic-shortcake getting around to this one. do you have a bracket that shows this bug?

**Comment by magic-shortcake** [comment]
https://animebracket.com/best-little-girl/stats
Pictured here are some examples from that bracket:
https://cdn.discordapp.com/attachments/924994434804908042/997379536540934154/unknown.png

**Comment by dxprog** [comment]
Thanks!

**Comment by dxprog** [comment]
Fixed!

**Comment by magic-shortcake** [comment]
I've noticed that it's been fixed in the example I sent, but it does not appear to be fixed in other brackets I've made.
Entrants eliminated by tie rule in my other brackets are now being labelled as the bracket winner.
https://cdn.discordapp.com/attachments/924994434804908042/998190406900658246/unknown.png

**Comment by dxprog** [comment]
Ah, looks like it was bad cache. Fixed.
