### ISSUE TITLE
Elimination round is not very friendly to multiple reddit accounts on same computer.

### ISSUE THREAD

**Issue by s4x0r** [dxprog/anime-bracket#8]
My friend and I are both voting from my computer. Even when clearing cache and cookies, and logging in to another account, his votes in the elimination round are still marked and there isn't a way for me to unmark them. Can't say much about the actual voting round as we have yet to reach that point.

**Comment by dxprog** [comment]
Sounds like a logout feature is needed. For the time being, you should be able to use a private/incognito window to get around that.

**Comment by dxprog** [comment]
Logout feature has been added and deployed.
