### ISSUE TITLE
If the user's account is not old enough for voting in a bracket, display the notification message sooner rather than at vote submission

### ISSUE THREAD

**Issue by antermin** [dxprog/anime-bracket#82]
Currently, the user is informed that their account is not old enough only when they try to submit their votes.

I hope the notification can be displayed sooner, and the checkboxes can also be disabled, to indicate that their account doesn't meet the voting requirements of that bracket, so that they don't have to waste time on voting and solving the reCAPTCHA.

**Comment by dxprog** [comment]
Added a modal on the voting page and deployed
