### ISSUE TITLE
[Enhancement] List of already nominated entries

### ISSUE THREAD

**Issue by AndreasSE93** [dxprog/anime-bracket#9]
It would be nice to know what entries have already been submitted during nomination (and not only the 9 in the preview image), especially so that you don't submit something that someone else has already submitted.

**Comment by chiefnoah** [comment]
Just change the "vote" or "results" part in the URL to "characters" (ie. [http://animebracket.com/results/best-girl-contest-2-22-the-salt-will-not-stop-coming-/](http://animebracket.com/results/best-girl-contest-2-22-the-salt-will-not-stop-coming-/) --> [http://animebracket.com/characters/best-girl-contest-2-22-the-salt-will-not-stop-coming-/](http://animebracket.com/characters/best-girl-contest-2-22-the-salt-will-not-stop-coming-/)) and it will list the already nominated characters. There probably should be a link to that on the nominations page though

**Comment by dxprog** [comment]
Agreed that the characters link needs to be actually public somewhere. However, it only displays characters that have already been approved by the bracket operators. Generally, nominated characters will run in the mid to high thousands, so it'd be very difficult to grok anything useful from that. I'll mull over how to better present this data.

**Comment by dxprog** [comment]
New nav fixes discover-ability issue here.
